//
// Created by wang on 2020/12/10.
//

#ifndef ERRORGENERATOR_ERRORTYPE_H
#define ERRORGENERATOR_ERRORTYPE_H

enum ErrorType {
    NORMAL, MEMORY_LEAK, MEM_ANOMAL_WITH_CPU, MEM_ANOMAL_WITH_NETWORK, MEM_ANOMAL_WITH_DISK, SERIOUS
};

#endif //ERRORGENERATOR_ERRORTYPE_H
