//
// Created by wang on 2020/12/10.
//

#ifndef ERRORGENERATOR_GENERATETYPE_H
#define ERRORGENERATOR_GENERATETYPE_H

enum GenerateType {
    NO_ACTION, LOW_LEVEL, HIGH_LEVEL, STEADY_UP_AND_KEEP, STEADY_UP_THEN_DOWN, BURST, BURST_WITH_FREQUENCY
};

#endif //ERRORGENERATOR_GENERATETYPE_H
